### ISSUE TITLE
Issue related to browser size while executing Nunit scripts via CCNET

### ISSUE THREAD

**Issue by Niranjan89** [ccnet/CruiseControl.NET#262]
I have integrated my Nunit automation scripts with Cruise control. Execution is working fine. I have used browser maximize code in my automation script but its not showing maximized size (1920x1080). While checking the output screenshot, it shows basic default size (1024x768). Since many functionalities are getting failed because of this browser size.

**Comment by lsvhome** [comment]
It isn't CruiseControl issue. CC doesn't setup browser environment.
Small advice for author:
For investigating your issue log on as CruiseControl user (if you use CC as windows service) or run CC as application under current user and run your automation scripts.
