### ISSUE TITLE
The main www.cruisecontrolnet.org website is dead

### ISSUE THREAD

**Issue by obones** [ccnet/CruiseControl.NET#263]
When we go to http://www.cruisecontrolnet.org/ we get an error saying that the name cannot be resolved.
What is happening? Is there anyone here to have a look at that?

**Comment by RubenWillems** [comment]
Hi

The site has been shutdown. It's been a long time and there were no more
active devs.
I tried as long as possible to keep the project up, but it was no longer
doable.

The source is still available at github.

If you have more questions, feel free to contact me.

with kind regards
Ruben Willems

**Comment by obones** [comment]
Ok, sad to hear.
Where did all the people go? What do they use for in house msbuild automation?
I'm happy with the current CruiseControl.Net but I'm wondering what's the "hype" nowadays.

**Comment by nydehi** [comment]
Perhaps we should use this instead?

https://github.com/ccnet/CruiseControl.NET/wiki

**Comment by dten** [comment]
The latest downloads aren't available on here, seems a shame

**Comment by RubenWillems** [comment]
Hi

what location are you looking at?
The latest release is still available at :
https://sourceforge.net/projects/ccnet/


grts
Ruben

**Comment by dten** [comment]
Ah I looked at releases here on Guthub

**Comment by savornicesei** [comment]
@RubenWillems If you rename doc/ folder to /docs/ and go to project settings> GitHub Pages and select Source: master/docs then the whole site will be deployed on github.io

Best,
Simo

**Comment by RubenWillems** [comment]
That has been done, but what would the github.io link be?
I never used that

**Comment by mintsoft** [comment]
It would be https://ccnet.github.io/CruiseControl.NET

**Comment by RubenWillems** [comment]
works like a charm ;-)
thanks !

**Comment by RubenWillems** [comment]
Documentation site is up again on github, and we're using appveyor for integration builds.
