### ISSUE TITLE
How to build the installers?

### ISSUE THREAD

**Issue by dten** [ccnet/CruiseControl.NET#270]
Trying to do a new version (of a fork) but it's not clear how one would go about creating the installers. I see NSIS and nsi.template files. Looks like some things are supposed to be replaced in the template and then nsis run on it but not had any luck. Pointers appreciated :)

**Comment by savornicesei** [comment]
@dten 
You need to run the build.bat / build-all.bat and build-package.bat (.sh ones if you're running them on linux)

**Comment by dten** [comment]
Ah thanks, that got further, nicely populated Dist directory now. Can't see how to actually call nsis properly though. i have tried

- Copying cctray.nsi.template to cctray.nsi and replacing @VERSION@ with a version number
- running `Tools\NSIS\NSIS.exe install\cctray.nsi`

but i'm just prompted with a white box, which is more than before :)

![image](https://user-images.githubusercontent.com/1019038/56952652-b45c5e80-6b32-11e9-954e-9921a758bb89.png)

**Comment by dten** [comment]
Oh sorry i realise i'm supposed to run `makensis.exe` but i get the following end of log 

```SetCompressor: lzma
!define: "MUI_ABORTWARNING"=""
!define: "MUI_ICON"="project\CCTrayLib\ResourceIcons\Green.ico"
!define: "MUI_UNICON"="project\CCTrayLib\ResourceIcons\Green.ico"
!define: "MUI_HEADERIMAGE"=""
!define: "MUI_HEADERIMAGE_BITMAP"="install\install_logo.bmp"
!define: "MUI_HEADERIMAGE_RIGHT"=""
!define: "MUI_COMPONENTSPAGE_SMALLDESC"=""
!insertmacro: MUI_PAGE_WELCOME
Error: File doesn't exist or is an invalid icon file
Error in macro MUI_INTERFACE on macroline 61
Error in macro MUI_PAGE_INIT on macroline 3
Error in macro MUI_PAGE_WELCOME on macroline 5
Error in script "install\ccnet.nsi" on line 34 -- aborting creation process```

**Comment by dten** [comment]
tried updating nsis and get a clearer error.

```
...
SetCompressor: lzma
!define: "MUI_ABORTWARNING"=""
!define: "MUI_ICON"="project\CCTrayLib\ResourceIcons\Green.ico"
!define: "MUI_UNICON"="project\CCTrayLib\ResourceIcons\Green.ico"
!define: "MUI_HEADERIMAGE"=""
!define: "MUI_HEADERIMAGE_BITMAP"="install\install_logo.bmp"
!define: "MUI_HEADERIMAGE_RIGHT"=""
!define: "MUI_COMPONENTSPAGE_SMALLDESC"=""
!insertmacro: MUI_PAGE_WELCOME
Error while loading icon from "project\CCTrayLib\ResourceIcons\Green.ico": can't open file
Error in macro MUI_INTERFACE on macroline 64
Error in macro MUI_PAGE_INIT on macroline 2
Error in macro MUI_PAGE_WELCOME on macroline 5
Error in script "..\..\install\cctray.nsi" on line 35 -- aborting creation process
```

which lead me to beleive it wants some relative path. 

moved cctray.nsi to the root directory and it worked 👍

**Comment by savornicesei** [comment]
@dten I'm glad that you've sorted it out.

The build-package.bat should have created the installer. See target 'packageCCTray' in /Tools/ccnet-packaging.inc.build that's included in the main ccnet.build script.
