### ISSUE TITLE
CruiseControl.Net add undesired “RetrieveBuildFile.aspx?file=” to <link> in html files

### ISSUE THREAD

**Issue by fractalocity** [ccnet/CruiseControl.NET#278]
I am trying to add a *.html ExtentReport to integration tests in CruiseControl.net.

I am able to do this, but the html file is not displayed correctly in CruiseControl.Net because CruiseControl.Net adds a “RetrieveBuildFile.aspx?file=” to all the link tags.

**Question**: How do I get CruiseControl.Net to stop adding this text to the *.html files? If this cannot be disabled, this should probably be considered an issue. 

The html report is unreadable when displayed in CruiseControl.net

Part of the source code after CruiseControl adds undesired retrievebuildfile:

I would show the code but the html tags don't seem to render correctly 

What the *.html looks like when not in CCNet:
    `<html>`
   `<head>`
   `<meta charset="utf-8">`
   `<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`
   `<title>Extent Framework</title>`
   `<link rel="shortcut icon" href="https://cdn.rawgit.com/extent-framework/extent-github-cdn/d74480e/commons/img/logo.png">`
   `<link rel="stylesheet" href="https://cdn.rawgit.com/extent-framework/extent-github-cdn/6cbbfb3/spark/css/styles.css" />`
   `<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">`
   `<style> </style>`
   `</head>`

What the *.html looks like when integrated into CCNet website:

--
`<!DOCTYPE html>`
   `<html>`
   `<head>`
   `<meta charset="utf-8">`
   `<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`
   `<title>Extent Framework</title>`
   `<link rel="shortcut icon" href="RetrieveBuildFile.aspx?file=https://cdn.rawgit.com/extent-framework/extent-github-cdn/d74480e/commons/img/logo.png">`
   `<link rel="stylesheet" href="RetrieveBuildFile.aspx?file=https://cdn.rawgit.com/extent-framework/extent-github-cdn/6cbbfb3/spark/css/styles.css" />`
   `<link href="RetrieveBuildFile.aspx?file=https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">`
   `<style> </style>`
   `</head>`

`

**Comment by mintsoft** [comment]
I think this either isn't possible (if it's this code: https://github.com/ccnet/CruiseControl.NET/blob/3cf8be76d80b9984984b8f42c6035745ac0381b9/project/WebDashboard/Dashboard/Actions/HtmlReportAction.cs#L54)  or it looks like you need to make it hit the regex here: https://github.com/ccnet/CruiseControl.NET/blob/3cf8be76d80b9984984b8f42c6035745ac0381b9/project/WebDashboard/Plugins/BuildReport/BuildFileDownload.cs#L45 so that it doesn't append the RetrieveBuildFile. Does it do it with `http://` ?

**Comment by fractalocity** [comment]
@mintsoft thanks for the tip. After looking at the code, I think it is the second options which is causing these side affects. Like you say, it doesn't have an options for accepting https:// without modifications. 

I think I'm going to have to abandon using ExtentReports in CruiseControl.Net and instead use it's predecessor, ReportUnit. The ReportUnit project does require access to any https:// information. Thanks again.
