### ISSUE TITLE
Fix PR: Change NUnit v2 to v3

### ISSUE THREAD

**Issue by savornicesei** [ccnet/CruiseControl.NET#286]
The existing PR #259 is mergeable BUT:

- nunit references must be changed to NuGet ones
- NUnit folder from Tools must be deleted
- make sure tests run

This is a must for linux build
```
     [exec]   Core/SourceControl/Mercurial/StubFileSystemTest.cs(11,3): error CS0619: 'TestFixtureAttribute' is obsolete: 'The NUnit framework shipped with Mono is deprecated and will be removed in a future release. It was based on NUnit 2.4 which is long outdated. Please move to the NUnit NuGet package or some other form of acquiring NUnit.' [/data/Proiecte/OSS/CruiseControl.NET/CruiseControl.NET_2/project/UnitTests/UnitTests.csproj]
     [exec]   Core/Util/RegistryTest.cs(8,3): error CS0619: 'TestFixtureAttribute' is obsolete: 'The NUnit framework shipped with Mono is deprecated and will be removed in a future release. It was based on NUnit 2.4 which is long outdated. Please move to the NUnit NuGet package or some other form of acquiring NUnit.' [/data/Proiecte/OSS/CruiseControl.NET/CruiseControl.NET_2/project/UnitTests/UnitTests.csproj]
```

**Comment by savornicesei** [comment]
@RubenWillems, @obones, @mintsoft 
Any ideas why I would have 4 tests failing in VS 2019 and 49 tests failing when running them from the build script (W10, VS2019 CE)?

Most of them are related to xml serialization - the namespaces are not in the expected order.
I've updated the build script to use the latest version of MSBuild available but somehow it still runs on 4.0!?! (it does not recognize ToolsVersion 15.0) 
I have installed 4.0 SDK after VS2019 - I might do a VS2019 repair this evening just to be sure references or registries did not go bananas.

Any ideas are highly appreciated.

**Comment by RubenWillems** [comment]
I've had similar things in the past.
can you make a PR with the stuff you have now?
so I can help looking into it?

In the past it was that somewhere in the build script a line forced an
older version of MSBuild to be used,
that involved line was duplicated between the build definitions (debug,
release, test) and not all places were updated.

grts
Ruben Willems

**Comment by mintsoft** [comment]
@savornicesei I've seen that before when a reference is updated and has added a binding redirect to the `app.config`, however the tests haven't had that binding redirect applied as it needs to be added to the nunit runner's `.config` instead.

On AppVeyor https://ci.appveyor.com/project/ccnet/cruisecontrol-net/builds/30297266 it looks like it's actually working but the attribute order is different now. Is that the same as you're seeing in VS?

**Comment by savornicesei** [comment]
@mintsoft I'll check tomorrow the assembly bindings.
For the inversed xml namespaces I was thinking of trying FluentAssertion because it has some xml assertions. Here we don't care about the ns index, just about their existence.

There are also 2 tests failing because the change datetimes do not match up to the last digit of the milisecond. Did they ever pass?

**Comment by mintsoft** [comment]
@savornicesei 

> There are also 2 tests failing because the change datetimes do not match up to the last digit of the milisecond. Did they ever pass?

Which ones? I can't see that in the build output anywhere; there's only the 47 XML tests.

(I *think* last I built ccnet from source and ran all the tests on VS2015 all the tests were green, but it was a few years ago so I might be wrong)

**Comment by RubenWillems** [comment]
Hi all

the Within keyword can be used to specify tolerances :
https://stackoverflow.com/questions/3577856/nunit-assert-areequal-datetime-tolerances/7601507#7601507

DateTime now = DateTime.Now;DateTime later = now + TimeSpan.FromHours(1.0);
Assert.That(now, Is.EqualTo(now) );Assert.That(later,
Is.EqualTo(now).Within(TimeSpan.FromHours(3.0)));*Assert.That(later,
Is.EqualTo(now).Within(3).Hours);*


Take a tolerance of 1 second for example.

grts
Ruben Willems

**Comment by savornicesei** [comment]
@RubenWillems , @mintsoft Thank you for your input!

Everything revolves around this ticket (looking at you, #271 ) so I want to get it done as soon as possible. 
Feel free to code review it as the changes have larger scope that the one defined by the issue title.

**Comment by savornicesei** [comment]
Uhh! Ohhh!
![image](https://user-images.githubusercontent.com/917232/73104009-10a3b180-3efe-11ea-9949-b26465584e6f.png)

My greatest work's completed!

**Comment by savornicesei** [comment]
Done
