### ISSUE TITLE
Upgrade Cake to 0.37 to avoid issue with latest Mono

### ISSUE THREAD

**Issue by obones** [ccnet/CruiseControl.NET#296]
Under Linux, cake has an issue with the latest mono, it gives this error: 
> Error: The assembly name is invalid.

Luckily, this has already been reported and fixed: https://github.com/cake-build/cake/issues/2695

As such, I believe CCNet should move to the 0.37 version

**Comment by obones** [comment]
Here is a pull request: https://github.com/ccnet/CruiseControl.NET/pull/297

**Comment by savornicesei** [comment]
Merged.

Thanks, @obones !
