### ISSUE TITLE
Most Linux file systems are case sensitive

### ISSUE THREAD

**Issue by obones** [ccnet/CruiseControl.NET#298]
Under Linux, most file systems are case sensitive, which means that all file references must respect case.
For instance, assembly references ultimately lead to finding a file from disk, which means using `System.configuration` will not work because the available file is `System.Configuration.dll` (notice the capital C)

There are various locations in CCNet which have this type of inconsistency, a pull request will follow.

**Comment by savornicesei** [comment]
@obones  Out of curiosity, what distro are you using for testing?

**Comment by obones** [comment]
I'm testing it with Manjaro Linux, an Arch Linux derivative where `mono --version` gives this:

```
Mono JIT compiler version 6.10.0 (makepkg/5d03a6fe116 Wed 15 Jul 2020 03:01:56 PM -03)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

```

**Comment by savornicesei** [comment]
Cool. I'll check your PRs later this evening on my openSUSE Tumbleweed.
